// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   float32
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	Amount    float32
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	Amount        float32
	CreatedAt     time.Time
}
